name: Build test.cpp as DLL on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MSVC
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat"

    - name: Compile test.cpp as DLL
      run: cl /LD /EHsc src/test.cpp /Fe:src/test.dll

    - name: List output files
      run: dir src
